# Generated by Django 4.2.16 on 2024-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('total_spent', models.FloatField(default=0.0)),
                ('discounts_available', models.IntegerField(default=0)),
                ('total_savings', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'customer_info',
            },
        ),
    ]
