# Generated by Django 4.2.16 on 2024-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveKitchenOrders',
            fields=[
                ('entryid', models.IntegerField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'active_kitchen_orders',
            },
        ),
    ]
